repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
    -   id: black
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--force-single-line-imports]
-   repo: https://github.com/uktrade/pii-secret-check-hooks
    rev: 0.0.0.35
    hooks:
    -   id: pii_secret_filename
        files: ''
        language: python
        pass_filenames: true
        require_serial: true
    -   id: pii_secret_file_content
        files: ''
        language: python
        pass_filenames: true
        require_serial: true
    -   id: pii_secret_file_content_ner
        files: ''
        language: python
        # args: [--ner_output_file=ner_output_file.txt] # uncomment to output NER entities
        pass_filenames: true
        require_serial: true
    -   id: hooks_version_check
        name: Checking local hooks against latest release
        verbose: true
        require_serial: true
