version: "3.8"
services:
    db:
        image: postgres:16.1
        volumes:
            - ./pgdata/:/var/lib/postgresql/data
        env_file:
            -   local.env
        ports:
            - "15432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U postgres" ]
            interval: 2s
            timeout: 6s
            retries: 5

    web:
        build: .
        command:
            - /bin/bash
            - -c
            - |
                python manage.py migrate --noinput
                python manage.py collectstatic --noinput
                python manage.py runserver 0.0.0.0:8000
        env_file:
            -   local.env
        ports:
            - "18000:8000"
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - .:/code

    redis:
        image: redis:7.2.4
        volumes:
            - ./redis_data:/data
        ports:
            - "16379:6379"