# Generated by Django 4.2.11 on 2024-04-04 10:34

from django.db import migrations
from django.conf import settings


def insert_sites(apps, schema_editor):
    """Populate the sites model"""
    Site = apps.get_model("sites", "Site")
    Site.objects.all().delete()

    # Register SITE_ID = 1
    Site.objects.create(domain=settings.RAB_DOMAIN, name="report-a-breach")
    # Register SITE_ID = 2
    Site.objects.create(domain=settings.VAB_DOMAIN, name="view-a-breach")


class Migration(migrations.Migration):

    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [migrations.RunPython(insert_sites)]
