# Generated by Django 4.2.10 on 2024-02-14 13:29

import uuid

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Breach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "reporter_professional_relationship",
                    models.TextField(
                        choices=[
                            (
                                "owner",
                                "I'm an owner, officer or employee of the company, or I am the person",
                            ),
                            (
                                "acting",
                                "I do not work for the company, but I'm acting on their behalf to make a voluntary declaration",
                            ),
                            (
                                "third_party",
                                "I work for a third party with a legal responsibility to make a mandatory declaration",
                            ),
                            (
                                "no_professional_relationship",
                                "I do not have a professional relationship with the company or person or I no longer have a professional relationship with them",
                            ),
                        ],
                        verbose_name="What is the professional relationship with the company or person suspected of breaching sanctions?",
                    ),
                ),
                (
                    "reporter_email_address",
                    models.EmailField(max_length=254, verbose_name="What is your email address?"),
                ),
                ("reporter_full_name", models.TextField(verbose_name="What is your full name?")),
                (
                    "additional_information",
                    models.TextField(verbose_name="Tell us about the suspected breach"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SanctionsRegime",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("short_name", models.TextField()),
                ("full_name", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UploadedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to="")),
                (
                    "breach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report_a_breach.breach"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SanctionsRegimeBreachThrough",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "breach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report_a_breach.breach"
                    ),
                ),
                (
                    "sanctions_regime",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="report_a_breach.sanctionsregime",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="PersonOrCompany",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "person_or_company",
                    models.CharField(
                        choices=[("person", "Person"), ("company", "Company")], max_length=7
                    ),
                ),
                ("name", models.TextField()),
                ("website", models.URLField(null=True)),
                ("address_line_1", models.TextField()),
                ("address_line_2", models.TextField(null=True)),
                ("address_line_3", models.TextField(null=True)),
                ("address_line_4", models.TextField(null=True)),
                ("town_or_city", models.TextField()),
                ("county", django_countries.fields.CountryField(max_length=2)),
                ("postcode", models.TextField()),
                (
                    "type_of_relationship",
                    models.CharField(
                        choices=[
                            ("breacher", "Breacher"),
                            ("supplier", "Supplier"),
                            ("recipient", "Recipient"),
                        ],
                        max_length=9,
                    ),
                ),
                (
                    "breach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="report_a_breach.breach"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="breach",
            name="sanctions_regimes",
            field=models.ManyToManyField(
                through="report_a_breach.SanctionsRegimeBreachThrough",
                to="report_a_breach.sanctionsregime",
            ),
        ),
    ]
