# Generated by Django 4.2.11 on 2024-03-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="breach",
            name="other_sanctions_regime",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="other_sanctions_regime",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
