# Generated by Django 4.2.10 on 2024-02-23 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breach",
            name="sanctions_regimes",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                through="report_a_breach.SanctionsRegimeBreachThrough",
                to="report_a_breach.sanctionsregime",
            ),
        ),
        migrations.AlterField(
            model_name="sanctionsregimebreachthrough",
            name="sanctions_regime",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report_a_breach.sanctionsregime",
            ),
        ),
    ]
