# Generated by Django 4.2.10 on 2024-02-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpersonorcompany",
            name="county",
        ),
        migrations.RemoveField(
            model_name="personorcompany",
            name="county",
        ),
        migrations.AddField(
            model_name="historicalpersonorcompany",
            name="when_did_you_first_suspect",
            field=models.TextField(
                default="",
                verbose_name="When did you first suspect the business or person had breached trade sanctions?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personorcompany",
            name="when_did_you_first_suspect",
            field=models.TextField(
                default="",
                verbose_name="When did you first suspect the business or person had breached trade sanctions?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="address_line_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="address_line_3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="address_line_4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="name",
            field=models.TextField(verbose_name="Name of business or person"),
        ),
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website address"),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="address_line_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="address_line_3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="address_line_4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="name",
            field=models.TextField(verbose_name="Name of business or person"),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="website",
            field=models.URLField(blank=True, null=True, verbose_name="Website address"),
        ),
    ]
