# Generated by Django 4.2.10 on 2024-02-27 12:20

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_remove_historicalpersonorcompany_county_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpersonorcompany",
            name="country",
            field=django_countries.fields.CountryField(default="gb", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalpersonorcompany",
            name="county",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="personorcompany",
            name="country",
            field=django_countries.fields.CountryField(default="GB", max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="personorcompany",
            name="county",
            field=models.TextField(null=True),
        ),
    ]
