# Generated by Django 4.2.11 on 2024-03-06 15:51

from django.db import migrations, models
import django_chunk_upload_handlers.clam_av


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_remove_historicalpersonorcompany_reference_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluploadeddocument",
            name="file",
            field=models.TextField(max_length=100, validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result]),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="file",
            field=models.FileField(upload_to="", validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result]),
        ),
    ]
