# Generated by Django 4.2.9 on 2024-01-29 09:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_breach_personorcompany_sanctionsregime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breach",
            name="sanctions_regimes",
        ),
    ]
