# Generated by Django 4.2.10 on 2024-02-20 16:37

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_breach_what_were_the_goods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalbreach",
            name="what_were_the_goods",
            field=models.TextField(
                default="",
                verbose_name="What were the goods or services, or what was the technological assistance or technology?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalsanctionsregime",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="sanctionsregime",
            name="date_range",
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
    ]
