# Generated by Django 4.2.10 on 2024-02-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_breach_what_were_the_goods_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breach",
            name="business_registered_with_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")],
                default="yes",
                max_length=11,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="business_registered_with_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")],
                default="yes",
                max_length=11,
            ),
            preserve_default=False,
        ),
    ]
