# Generated by Django 4.2.9 on 2024-01-31 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0003_remove_breach_sanctions_regimes"),
    ]

    operations = [
        migrations.AddField(
            model_name="breach",
            name="sanctions_regimes",
            field=models.ManyToManyField(
                through="report_a_breach.SanctionsRegimeBreachThrough",
                to="report_a_breach.sanctionsregime",
            ),
        ),
    ]
