# Generated by Django 4.2.10 on 2024-02-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0003_breach_business_registered_with_companies_house_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="breach",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=3
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="breach",
            name="registered_company_number",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")], default="yes", max_length=3
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="registered_company_number",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
