# Generated by Django 4.2.10 on 2024-02-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0003_historicalsanctionsregimebreachthrough_unknown_regime_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalsanctionsregimebreachthrough",
            name="unknown_regime",
        ),
        migrations.RemoveField(
            model_name="sanctionsregimebreachthrough",
            name="unknown_regime",
        ),
        migrations.AddField(
            model_name="breach",
            name="unknown_sanctions_regime",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="unknown_sanctions_regime",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
