# Generated by Django 4.2.10 on 2024-02-21 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0003_historicalbreach_what_were_the_goods"),
        ("report_a_breach", "0003_historicalbreach_what_were_the_goods_and_more"),
    ]

    operations = []
