# Generated by Django 4.2.10 on 2024-02-27 12:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0003_historicalpersonorcompany_country_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpersonorcompany",
            old_name="postcode",
            new_name="postal_code",
        ),
        migrations.RenameField(
            model_name="personorcompany",
            old_name="postcode",
            new_name="postal_code",
        ),
    ]
