# Generated by Django 4.2.10 on 2024-02-06 15:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0002_historicaluploadeddocument_and_more"),
        ("report_a_breach", "0004_breach_sanctions_regimes"),
    ]

    operations = []
