# Generated by Django 4.2.10 on 2024-02-19 17:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0004_breach_do_you_know_the_registered_company_number_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="breach",
            name="business_registered_with_companies_house",
        ),
        migrations.RemoveField(
            model_name="historicalbreach",
            name="business_registered_with_companies_house",
        ),
        migrations.AddField(
            model_name="breach",
            name="business_registered_on_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")],
                default="yes",
                max_length=11,
                verbose_name="Are you reporting a business which is registered with Companies House?",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="business_registered_on_companies_house",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No"), ("do_not_know", "I do not know")],
                default="yes",
                max_length=11,
                verbose_name="Are you reporting a business which is registered with Companies House?",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="breach",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                verbose_name="Do you know the registered company number?",
            ),
        ),
        migrations.AlterField(
            model_name="historicalbreach",
            name="do_you_know_the_registered_company_number",
            field=models.CharField(
                choices=[("yes", "Yes"), ("no", "No")],
                max_length=3,
                verbose_name="Do you know the registered company number?",
            ),
        ),
    ]
