# Generated by Django 4.2.10 on 2024-02-27 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "report_a_breach",
            "0004_remove_historicalsanctionsregimebreachthrough_unknown_regime_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="breach",
            name="sanctions_regimes",
            field=models.ManyToManyField(
                blank=True,
                through="report_a_breach.SanctionsRegimeBreachThrough",
                to="report_a_breach.sanctionsregime",
            ),
        ),
    ]
