# Generated by Django 4.2.10 on 2024-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("report_a_breach", "0005_alter_breach_sanctions_regimes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breach",
            name="unknown_sanctions_regime",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="historicalbreach",
            name="unknown_sanctions_regime",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
