from report_a_suspected_breach.models import Breach

from tests.test_frontend.conftest import PlaywrightTestBase


class TestSameBreacherSupplierPath(PlaywrightTestBase):
    def test_same_supplier_breacher(self):
        page = self.page
        Breach.objects.all().delete()
        assert Breach.objects.all().count() == 0
        page.get_by_role("link", name="Your details").click()
        page.get_by_label("I do not work for the").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("What is your email address?").click()
        page.get_by_label("What is your email address?").fill("chris.pettinga@digital.trade.gov.uk")
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("Enter the 6 digit security").click()
        page.get_by_label("Enter the 6 digit security").fill("353152")
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("What is your full name?").click()
        page.get_by_label("What is your full name?").fill("Chris ")
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("link", name="2. About the person or").click()
        page.get_by_label("Yes").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("Yes").check()
        page.get_by_label("Registered company number").click()
        page.get_by_label("Registered company number").fill(" 00233462")
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("link", name="Overview of the suspected breach").click()
        page.get_by_label("Day").click()
        page.get_by_label("Day").fill("1")
        page.get_by_label("Month").click()
        page.get_by_label("Month").fill("1")
        page.get_by_label("Year").click()
        page.get_by_label("Year").fill("14")
        page.get_by_label("Approximate date").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("The Afghanistan (Sanctions) (").check()
        page.get_by_label("I do not know").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("What were the goods or").click()
        page.get_by_label("What were the goods or").fill("this isa. short description")
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("link", name="The supply chain").click()
        page.get_by_label("1 Drummond Gate, Pimlico,").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("The UK", exact=True).check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("Name of person (optional)").click()
        page.get_by_label("Name of person (optional)").fill("End User 1")
        page.get_by_label("Name of business (optional)").click()
        page.get_by_label("Name of business (optional)").fill("end user ltd")
        page.get_by_label("Email address (optional)").click()
        page.get_by_label("Email address (optional)").fill("enduser@example.com")
        page.get_by_label("Website address (optional)").click()
        page.get_by_label("Website address (optional)").fill("www.enduser1.com")
        page.get_by_label("Address line 1 (optional)").click()
        page.get_by_label("Address line 1 (optional)").fill("12 end user road")
        page.get_by_label("Address line 2 (optional)").click()
        page.get_by_label("Address line 2 (optional)").fill("end user flat")
        page.get_by_label("Town or city (optional)").click()
        page.get_by_label("Town or city (optional)").fill("london")
        page.get_by_label("County (optional)").click()
        page.get_by_label("County (optional)").fill("greater london")
        page.get_by_label("Postcode (optional)").click()
        page.get_by_label("Postcode (optional)").fill("sw1a 1aa")
        page.get_by_label("Additional contact details (").click()
        page.get_by_label("Additional contact details (").fill("fax machine: 12345")
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("No").check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("No", exact=True).check()
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("link", name="Sanctions breach details").click()
        page.get_by_role("button", name="Continue").click()
        page.get_by_label("Give a summary of the breach").click()
        page.get_by_label("Give a summary of the breach").fill("summary of the breach")
        page.get_by_role("button", name="Continue").click()
        page.get_by_role("link", name="Continue").click()
        page.get_by_role("link", name="Continue").click()
        page.get_by_label("I agree and accept").check()
        page.get_by_role("button", name="Submit").click()
