import re

from playwright.sync_api import expect

from .. import conftest


class TestWhenDidYouFirstSuspect(conftest.PlaywrightTestBase):
    """
    Tests for when did you first suspect page
    """

    def test_correct_input_returns_which_sanctions_regimes(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_label("Day").click()
        self.page.get_by_label("Day").fill("12")
        self.page.get_by_label("Month").click()
        self.page.get_by_label("Month").fill("12")
        self.page.get_by_label("Year").click()
        self.page.get_by_label("Year").fill("2023")
        self.page.get_by_role("heading", name="Is the date you entered exact").click()
        self.page.get_by_label("Exact date").check()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page).to_have_url(re.compile(r".*/which_sanctions_regime"))

    def test_future_date_returns_error(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_label("Day").click()
        self.page.get_by_label("Day").fill("12")
        self.page.get_by_label("Month").click()
        self.page.get_by_label("Month").fill("12")
        self.page.get_by_label("Year").click()
        self.page.get_by_label("Year").fill("3025")
        self.page.get_by_role("heading", name="Is the date you entered exact").click()
        self.page.get_by_label("Exact date").check()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page.get_by_role("heading", name="There is a problem")).to_be_visible()
        expect(self.page.get_by_role("link", name="The date you first suspected the breach must be in the past")).to_be_visible()
        expect(self.page).to_have_url(re.compile(r".*/when_did_you_first_suspect"))

    def test_incorrect_date_returns_error(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_label("Day").click()
        self.page.get_by_label("Day").fill("123")
        self.page.get_by_label("Month").click()
        self.page.get_by_label("Month").fill("12")
        self.page.get_by_label("Year").click()
        self.page.get_by_label("Year").fill("2025")
        self.page.get_by_role("heading", name="Is the date you entered exact").click()
        self.page.get_by_label("Exact date").check()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page.get_by_role("heading", name="There is a problem")).to_be_visible()
        expect(self.page.get_by_role("link", name="The date you first suspected the breach must be a real date")).to_be_visible()
        expect(self.page).to_have_url(re.compile(r".*/when_did_you_first_suspect"))

    def test_no_exact_date_returns_error(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_role("heading", name="Is the date you entered exact").click()
        self.page.get_by_label("Exact date").check()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page.get_by_role("heading", name="There is a problem")).to_be_visible()
        expect(self.page.get_by_role("link", name="Enter the exact date")).to_be_visible()
        expect(self.page).to_have_url(re.compile(r".*/when_did_you_first_suspect"))

    def test_no_approx_date_returns_error(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_role("heading", name="Is the date you entered exact").click()
        self.page.get_by_label("Approximate date").check()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page.get_by_role("heading", name="There is a problem")).to_be_visible()
        expect(self.page.get_by_role("link", name="Enter the approximate date")).to_be_visible()
        expect(self.page).to_have_url(re.compile(r".*/when_did_you_first_suspect"))

    def test_no_input_returns_error(self):
        self.page.goto("http://report-a-suspected-breach:8000/report_a_suspected_breach/")
        self.page.get_by_role("link", name="Reset session").click()
        self.page.get_by_role("link", name="Your details").click()
        self.create_reporter_details(self.page, "I'm an owner")
        self.page.get_by_role("link", name="2. About the person or").click()
        self.create_non_uk_breacher(self.page)
        self.page.get_by_role("link", name="Overview of the suspected breach").click()
        self.page.get_by_role("heading", name="Date you first suspected the").click()
        self.page.get_by_role("heading", name="Enter the exact date or an").click()
        self.page.get_by_role("button", name="Continue").click()
        expect(self.page.get_by_role("heading", name="There is a problem")).to_be_visible()
        expect(
            self.page.get_by_role("link", name="Select whether you know the exact date, or the approximate date")
        ).to_be_visible()
        expect(self.page).to_have_url(re.compile(r".*/when_did_you_first_suspect"))
