"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
import sentry_sdk
from django.urls import reverse_lazy
from sentry_sdk.integrations.django import DjangoIntegration

from config.env import env

is_dbt_platform = "COPILOT_ENVIRONMENT_NAME" in os.environ

BASE_DIR = Path(__file__).resolve().parent.parent.parent

SECRET_KEY = env.django_secret_key

DEBUG = env.debug

ALLOWED_HOSTS = env.allowed_hosts

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",
]

OUR_APPS = ["report_a_breach", "healthcheck"]

THIRD_PARTY_APPS = [
    "crispy_forms",
    "crispy_forms_gds",
    "django_chunk_upload_handlers",
    "simple_history",
    "storages",
    "authbroker_client",
]

INSTALLED_APPS = DJANGO_APPS + OUR_APPS + THIRD_PARTY_APPS

CRISPY_ALLOWED_TEMPLATE_PACKS = ("bootstrap", "bootstrap3", "bootstrap4", "uni_form", "gds")
CRISPY_TEMPLATE_PACK = "gds"

# AWS
AWS_S3_REGION_NAME = env.aws_default_region
AWS_ENDPOINT_URL = env.aws_endpoint_url

# General S3
AWS_S3_OBJECT_PARAMETERS = {"ContentDisposition": "attachment"}
PRESIGNED_URL_EXPIRY_SECONDS = env.presigned_url_expiry_seconds
AWS_S3_SIGNATURE_VERSION = "s3v4"
AWS_DEFAULT_ACL = "private"

# Temporary document bucket
TEMPORARY_S3_BUCKET_ACCESS_KEY_ID = env.temporary_s3_bucket_configuration["access_key_id"]
TEMPORARY_S3_BUCKET_SECRET_ACCESS_KEY = env.temporary_s3_bucket_configuration["secret_access_key"]
TEMPORARY_S3_BUCKET_NAME = env.temporary_s3_bucket_configuration["bucket_name"]

# Permanent document bucket
PERMANENT_S3_BUCKET_ACCESS_KEY_ID = env.permanent_s3_bucket_configuration["access_key_id"]
PERMANENT_S3_BUCKET_SECRET_ACCESS_KEY = env.permanent_s3_bucket_configuration["secret_access_key"]
PERMANENT_S3_BUCKET_NAME = env.permanent_s3_bucket_configuration["bucket_name"]


# Static files (CSS, JavaScript, Images)
STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "static"
STATICFILES_DIRS = (BASE_DIR / "report_a_breach" / "static",)

# Media Files Storage
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": {"bucket_name": env.temporary_s3_bucket_configuration["bucket_name"], "location": "media"},
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

# File storage
FILE_UPLOAD_HANDLERS = (
    "django_chunk_upload_handlers.clam_av.ClamAVFileUploadHandler",
    "report_a_breach.custom_upload_handler.CustomFileUploadHandler",
    "django.core.files.uploadhandler.MemoryFileUploadHandler",
    "django.core.files.uploadhandler.TemporaryFileUploadHandler",
)  # Order is important

# CLAM AV
CLAM_AV_USERNAME = env.clam_av_username
CLAM_AV_PASSWORD = env.clam_av_password
CLAM_AV_DOMAIN = env.clam_av_domain
CHUNK_UPLOADER_RAISE_EXCEPTION_ON_VIRUS_FOUND = False

# MIDDLEWARE
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "simple_history.middleware.HistoryRequestMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.media",
                "report_a_breach.sites.context_processors.sites",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"

# Database
DATABASES = {
    "default": {
        **dj_database_url.parse(
            env.database_uri,
            engine="postgresql",
            conn_max_age=0,
        ),
        "ENGINE": "django.db.backends.postgresql",
    }
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "authbroker_client.backends.AuthbrokerBackend",
]

LOGIN_URL = reverse_lazy("authbroker_client:login")
LOGIN_REDIRECT_URL = reverse_lazy("complete")

# Internationalization
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# COMPANIES HOUSE API
COMPANIES_HOUSE_API_KEY = env.company_house_api_key

# GOV NOTIFY
GOV_NOTIFY_API_KEY = env.gov_notify_api_key
EMAIL_VERIFY_CODE_TEMPLATE_ID = env.email_verify_code_template_id
RESTRICT_SENDING = env.restrict_sending  # if True, only send to whitelisted domains

# SENTRY
SENTRY_DSN = env.sentry_dsn
SENTRY_ENVIRONMENT = env.sentry_environment
if SENTRY_DSN and SENTRY_ENVIRONMENT:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        environment=SENTRY_ENVIRONMENT,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0,
    )

# Email Verification settings
EMAIL_VERIFY_TIMEOUT_SECONDS = env.email_verify_timeout_seconds

# Google Analytics
GTM_ENABLED = env.gtm_enabled
GTM_ID = env.gtm_id


MIGRATION_MODULES = {
    "sites": "report_a_breach.migrations.sites_migrations",
}

RAB_DOMAIN = "report-a-breach"
VAB_DOMAIN = "view-a-breach"

TEST_SSO_PROVIDER_SET_RETURNED_ACCESS_TOKEN = env.mock_sso_token
AUTHBROKER_URL = "http://localhost:8080"
AUTHBROKER_CLIENT_ID = "test_client"
AUTHBROKER_CLIENT_SECRET = "dummy-secret"
AUTHBROKER_TOKEN_SESSION_KEY = "_authbroker_token"
AUTHBROKER_STAFF_SSO_SCOPE = "dummy-scope"

MOCK_SSO_TOKEN = "dummy-token"
MOCK_SSO_SCOPE = "dummy-scope"
MOCK_SSO_USERNAME = "testuser"
MOCK_SSO_EMAIL_USER_ID = "testuser@example.com"

OAUTHLIB_INSECURE_TRANSPORT = env.oauthlib_insecure_transport
