# Generated by Django 4.2.13 on 2024-06-18 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreporteremailverification",
            name="verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reporteremailverification",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
