# Generated by Django 4.2.13 on 2024-06-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0002_historicalreporteremailverification_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="website",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="website",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
