# Generated by Django 4.2.15 on 2024-10-04 11:32

import core.document_storage
from django.db import migrations, models
import django_chunk_upload_handlers.clam_av


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0002_alter_historicaluploadeddocument_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaluploadeddocument",
            name="file",
            field=models.TextField(
                blank=True,
                max_length=340,
                null=True,
                validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result],
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=340,
                null=True,
                storage=core.document_storage.PermanentDocumentStorage(),
                upload_to="",
                validators=[django_chunk_upload_handlers.clam_av.validate_virus_check_result],
            ),
        ),
    ]
