# Generated by Django 4.2.17 on 2024-12-12 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0003_alter_historicaluploadeddocument_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="address_line_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="address_line_1",
            field=models.TextField(blank=True, null=True),
        ),
    ]
