# Generated by Django 4.2.13 on 2024-06-21 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0003_historicalreporteremailverification_verified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breach",
            name="reporter_email_verification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="report_a_suspected_breach.reporteremailverification",
            ),
        ),
    ]
