# Generated by Django 4.2.20 on 2025-05-27 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0004_whistleblower_alter_personorcompany_breach_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpersonorcompany",
            old_name="breach",
            new_name="breach_report",
        ),
        migrations.RenameField(
            model_name="personorcompany",
            old_name="breach",
            new_name="breach_report",
        ),
    ]
