# Generated by Django 4.2.20 on 2025-05-28 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0004_whistleblower_alter_personorcompany_breach_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicalpersonorcompany",
            old_name="breach",
            new_name="breach_report",
        ),
        migrations.RenameField(
            model_name="personorcompany",
            old_name="breach",
            new_name="breach_report",
        ),
        migrations.AddField(
            model_name="historicaluploadeddocument",
            name="whistleblower_report",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="report_a_suspected_breach.whistleblowerreport",
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="whistleblower_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report_a_suspected_breach.whistleblowerreport",
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="breach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="report_a_suspected_breach.breach",
            ),
        ),
        migrations.AlterField(
            model_name="whistleblower",
            name="email_verification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="report_a_suspected_breach.reporteremailverification",
            ),
        ),
    ]
