# Generated by Django 4.2.17 on 2024-12-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0004_alter_historicalpersonorcompany_address_line_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpersonorcompany",
            name="town_or_city",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="personorcompany",
            name="town_or_city",
            field=models.TextField(blank=True, null=True),
        ),
    ]
