# Generated by Django 4.2.14 on 2024-07-25 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sessions", "0001_initial"),
        ("report_a_suspected_breach", "0004_alter_breach_reporter_email_verification"),
    ]

    operations = [
        migrations.AddField(
            model_name="breach",
            name="reporter_session",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="sessions.session"),
        ),
        migrations.AddField(
            model_name="historicalbreach",
            name="reporter_session",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="sessions.session",
            ),
        ),
        migrations.AlterField(
            model_name="reporteremailverification",
            name="reporter_session",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="sessions.session"),
        ),
    ]
