# Generated by Django 4.2.20 on 2025-05-28 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0005_rename_breach_historicalpersonorcompany_breach_report_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaluploadeddocument",
            name="whistleblower_report",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="report_a_suspected_breach.whistleblowerreport",
            ),
        ),
        migrations.AddField(
            model_name="uploadeddocument",
            name="whistleblower_report",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="report_a_suspected_breach.whistleblowerreport",
            ),
        ),
        migrations.AlterField(
            model_name="uploadeddocument",
            name="breach",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="report_a_suspected_breach.breach",
            ),
        ),
    ]
