# Generated by Django 4.2.15 on 2024-08-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("report_a_suspected_breach", "0001_squashed_0006_remove_historicalsanctionsregimebreachthrough_breach_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="breach",
            name="reporter_professional_relationship",
            field=models.TextField(
                choices=[
                    ("owner", "I'm an owner, officer or employee of the business, or I am the person"),
                    (
                        "acting",
                        "I do not work for the business or person, but I'm acting on their behalf to make a voluntary declaration",
                    ),
                    ("third_party", "I work for a third party with a legal obligation to make a mandatory report"),
                    (
                        "no_professional_relationship",
                        "I do not have a professional relationship with the business or person, or I no longer have a professional relationship with them",
                    ),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalbreach",
            name="reporter_professional_relationship",
            field=models.TextField(
                choices=[
                    ("owner", "I'm an owner, officer or employee of the business, or I am the person"),
                    (
                        "acting",
                        "I do not work for the business or person, but I'm acting on their behalf to make a voluntary declaration",
                    ),
                    ("third_party", "I work for a third party with a legal obligation to make a mandatory report"),
                    (
                        "no_professional_relationship",
                        "I do not have a professional relationship with the business or person, or I no longer have a professional relationship with them",
                    ),
                ]
            ),
        ),
    ]
