# Generated by Django 4.2.13 on 2024-06-03 09:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackitem",
            name="did_you_experience_any_issues",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "I did not experience any issues"),
                    ("not_found", "I did not find what I was looking for"),
                    ("difficult", "I found it difficult to navigate"),
                    ("lacks_features", "The system lacks the feature I need"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalfeedbackitem",
            name="did_you_experience_any_issues",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "I did not experience any issues"),
                    ("not_found", "I did not find what I was looking for"),
                    ("difficult", "I found it difficult to navigate"),
                    ("lacks_features", "The system lacks the feature I need"),
                    ("other", "Other"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
