# Generated by Django 4.2.13 on 2024-06-17 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_remove_feedbackitem_did_you_experience_any_issues_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackitem",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeedbackitem",
            name="url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
