# Generated by Django 4.2.16 on 2024-12-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_feedbackitem_url_historicalfeedbackitem_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackitem",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="feedbackitem",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeedbackitem",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="historicalfeedbackitem",
            name="user_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
