# Generated by Django 4.2.16 on 2024-12-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedbackitem_user_email_feedbackitem_user_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackitem",
            name="rating",
            field=models.IntegerField(
                choices=[(5, "Very satisfied"), (4, "Satisfied"), (3, "Neutral"), (2, "Dissatisfied"), (1, "Very dissatisfied")]
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeedbackitem",
            name="rating",
            field=models.IntegerField(
                choices=[(5, "Very satisfied"), (4, "Satisfied"), (3, "Neutral"), (2, "Dissatisfied"), (1, "Very dissatisfied")]
            ),
        ),
    ]
