# Generated by Django 4.2.16 on 2025-01-23 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_feedbackitem_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackitem",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "Very satisfied"),
                    (4, "Satisfied"),
                    (3, "Neither satisfied nor dissatisfied"),
                    (2, "Dissatisfied"),
                    (1, "Very dissatisfied"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="historicalfeedbackitem",
            name="rating",
            field=models.IntegerField(
                choices=[
                    (5, "Very satisfied"),
                    (4, "Satisfied"),
                    (3, "Neither satisfied nor dissatisfied"),
                    (2, "Dissatisfied"),
                    (1, "Very dissatisfied"),
                ]
            ),
        ),
    ]
